#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  proxy_pass http://127.0.0.1:__PORT_FRONTEND__;
  proxy_buffer_size 8k;

  include proxy_params_no_auth;
  proxy_redirect    off;
  proxy_set_header  X-Forwarded-Port $server_port;
        
  proxy_pass_request_headers on;

  #WebSocket Support
  client_max_body_size 100M;
}

location /admin/ {
     proxy_pass http://127.0.0.1:8015;
     include proxy_params_no_auth;
     proxy_set_header X-Forwarded-Port  $server_port;
}

location /media/ {
  alias __INSTALL_DIR__/backend/server/media/;
}


location /static/ {
  alias __INSTALL_DIR__/backend/server/staticfiles/;
}

# Serve protected media files with X-Accel-Redirect
location /protectedMedia/ {
  internal; # Only internal requests are allowed
  alias __INSTALL_DIR__/backend/server/media/;  # This should match Django MEDIA_ROOT
  try_files $uri =404; # Return a 404 if the file doesn't exist
            
# Security headers for all protected files
more_set_headers "Content-Security-Policy: default-src 'self'; script-src 'none'; object-src 'none'; base-uri 'none'";
more_set_headers "X-Content-Type-Options: nosniff";
more_set_headers "X-Frame-Options: SAMEORIGIN";
more_set_headers "X-XSS-Protection: 1; mode=block";
more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
}
